export const cityContent = {
  "citrus-heights": {
    name: "Citrus Heights",
    metaTitle: "Home Services in Citrus Heights, CA",
    metaDescription: "Gutters, painting, handyman & remodeling for Citrus Heights homeowners.",
    heroTitle: "Citrus Heights Home Services, Repairs & Remodeling",
    heroSubtitle: "Local, professional service across Citrus Heights neighborhoods.",
    neighborhoods: ["Sunrise Ranch", "Arcade Creek", "Rusch Park", "Sunset Golf"],
  },
  roseville: {
    name: "Roseville",
    metaTitle: "Home Services in Roseville, CA",
    metaDescription: "Local team for gutters, painting, handyman & remodeling in Roseville.",
    heroTitle: "Roseville Home Services, Repairs & Remodeling",
    heroSubtitle: "Serving neighborhoods near Blue Oaks and throughout the city.",
    neighborhoods: ["Blue Oaks", "Fiddyment Farm", "Highland Reserve", "Ridgeview"],
  },
  rocklin: {
    name: "Rocklin",
    metaTitle: "Home Services in Rocklin, CA",
    metaDescription: "Trusted gutters, painting, handyman & remodeling for Rocklin homes.",
    heroTitle: "Rocklin Home Services, Repairs & Remodeling",
    heroSubtitle: "Near Rocklin Crossing and across the community.",
    neighborhoods: ["Stanford Ranch", "Whitney Oaks", "Sunset West", "Rocklin Ranch Golf Club"],
  },
  loomis: {
    name: "Loomis",
    metaTitle: "Home Services in Loomis, CA",
    metaDescription: "Professional home services and remodeling for Loomis.",
    heroTitle: "Loomis Home Services, Repairs & Remodeling",
    heroSubtitle: "Trusted local team serving Loomis homeowners.",
    neighborhoods: ["Loomis Basin", "Horseshoe Bar", "Taylor Road", "Granite Bay Estates"],
  },
  auburn: {
    name: "Auburn",
    metaTitle: "Home Services in Auburn, CA",
    metaDescription: "Local pros for Auburn home services and remodels.",
    heroTitle: "Auburn Home Services, Repairs & Remodeling",
    heroSubtitle: "Serving Auburn and surrounding foothill communities.",
    neighborhoods: ["Downtown Auburn", "North Auburn", "Hidden Falls", "Loch Lomond"],
  },
  folsom: {
    name: "Folsom",
    metaTitle: "Home Services in Folsom, CA",
    metaDescription: "Gutters, painting, handyman & remodeling for Folsom homes.",
    heroTitle: "Folsom Home Services, Repairs & Remodeling",
    heroSubtitle: "Professional service for Folsom neighborhoods.",
    neighborhoods: ["Empire Ranch", "Broadstone", "Historic Folsom", "Northridge"],
  },
  "granite-bay": {
    name: "Granite Bay",
    metaTitle: "Home Services in Granite Bay, CA",
    metaDescription: "Premium home services and remodeling for Granite Bay.",
    heroTitle: "Granite Bay Home Services, Repairs & Remodeling",
    heroSubtitle: "Quality-driven service for Granite Bay homeowners.",
    neighborhoods: ["Treelake", "Wexford", "Douglas Ranch", "Granite Bay Club"],
  },
  lincoln: {
    name: "Lincoln",
    metaTitle: "Home Services in Lincoln, CA",
    metaDescription: "Local pros for Lincoln home services and remodeling.",
    heroTitle: "Lincoln Home Services, Repairs & Remodeling",
    heroSubtitle: "Serving Lincoln neighborhoods with professional results.",
    neighborhoods: ["12 Bridges", "Lincoln Crossing", "Catta Verdera", "Riverside"],
  },
  sacramento: {
    name: "Sacramento",
    metaTitle: "Home Services in Sacramento, CA",
    metaDescription: "Gutters, painting, handyman & remodeling for Sacramento homes.",
    heroTitle: "Sacramento Home Services, Repairs & Remodeling",
    heroSubtitle: "Your complete home improvement partner across Sacramento.",
    neighborhoods: ["East Sacramento", "Land Park", "Natomas", "Greenhaven"],
  },
} as const;
